version: '3'

services:
  composer:
    image: composer:latest
    volumes:
      - .:/app
  phpunit:
    image: php:8.2-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit